version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrator
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/orchestrator
      # Optional OpenAI planner
      ORCH_ENABLE_OPENAI_PLANNER: ${ORCH_ENABLE_OPENAI_PLANNER:-false}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ORCH_OPENAI_MODEL: ${ORCH_OPENAI_MODEL:-gpt-4o-mini}
      ORCH_OPENAI_BASE_URL: ${ORCH_OPENAI_BASE_URL:-}
    ports:
      - "18080:8000"
    depends_on:
      db:
        condition: service_healthy
