version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrator
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/orchestrator
    ports:
      - "18080:8000"
    depends_on:
      db:
        condition: service_healthy
