apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: {{ .Values.namespace }}
spec:
  selector: { app: orchestrator }
  ports:
    - name: http
      port: 8000
      targetPort: 8000

