name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install test deps
        run: python -m pip install -r orchestrator/requirements.txt
      - name: Run tests (Docker e2e)
        run: python -m pytest -q
